### PR TITLE
Shift tab works to escape a menu.

### PR DESCRIPTION
**Pull request by cdata**
/cc @notwaldorf @blasten

### CODE REVIEW

**Comment by cdata** [comment]
I have updated this PR with a change that makes menus sensitive to `multi`, and applies `aria-multiselectable="true"` to the menu if appropriate.

**Comment by morethanreal** [comment]
This is awesome. lgtm, would like to see a test with the `aria-multiselectable` attribute.

**Comment by blasten** [comment]
Thanks for this!

**Comment by cdata** [comment]
I'm not sure why CI is showing massive failures. I have manually run the tests in Safari 7, Firefox, Chrome and IE10 - the test suite is green in all of these browsers.

**Pull request merged**
