### PR TITLE
Cast the rootTarget to ?HTMLElement for the compiler

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by bicknellr** [comment]
#55

**Comment by bicknellr** [comment]
Isn't this an issue with Polymer's declared return type for rootTarget?

**Comment by bicknellr** [comment]
Whichever of #54 / #55 changes to [`?HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/tabIndex) first gets merged.

**Comment by rictic** [comment]
Done!

**Comment by bicknellr** [comment]
Cool, tests are green, LGTM.

**Pull request merged**
