### PR TITLE
Property to opt out of focus() on _focusedItemChanged

### PR DESCRIPTION
**Pull request by jpodwys**
This PR goes with #96.

### CODE REVIEW

**Review by ruixiong — APPROVED** [review]

**Comment by jpodwys** [comment]
@bicknellr @notwaldorf @cdata @rictic

**Comment by jpodwys** [comment]
@robdodson I'm not sure who to tag here. Any suggestions?

**Comment by jpodwys** [comment]
Boy, what a roller coaster of anticipation this past month since I opened this PR has been. Not sure my tender heart can take any more. What say you we merge this little guy?

@bicknellr @notwaldorf @cdata @rictic

**Review by spacerockzero — APPROVED** [review]

**Comment by bicknellr** [comment]
I think this request might be better served by preventing [this line](https://github.com/PolymerElements/iron-menu-behavior/blob/cf68d76ebcfebd57d1a73e53c47845a9956506e1/iron-menu-behavior.html#L117) from asking to focus the item. I don't think it really makes sense to disable the focusing behavior in the observer for `focusedItem` itself, since that's pretty much the only point of setting it. It seems reasonable not to want to focus when selecting an item though - maybe replacing that line with something like `this._setFocusedItem(this.theNewPropertyName ? item : null)` is closer to what you're looking for? Is calling `select` the only case that this is a problem?

**Comment by bicknellr** [comment]
I just noticed that IronMultiSelectableBehavior and IronSelectableBehavior are inconsistent in how they handle `fallbackSelection`: [the first uses `select`](https://github.com/PolymerElements/iron-selector/blob/7cff698141426aee2e9e4deead305ef8016bf422/iron-multi-selectable.html#L125) and [the second sets `selected`](https://github.com/PolymerElements/iron-selector/blob/7cff698141426aee2e9e4deead305ef8016bf422/iron-selectable.html#L310). Maybe we should update IronMultiSelectableBehavior to set `selected` instead?

**Comment by jpodwys** [comment]
I'm currently selecting the first item with `.select(0)`. I tried switching to `.selected = 0` and that seems to help a lot. I still see glitches sometimes, but I'm not certain where they're coming from. Regardless, it's objectively better than what I currently have.

As for your proposed change to `iron-multi-selectable`, I'm still pinned to `1.x` of the component which is significantly different, so I wasn't able to check if that fix would work for me.

**Comment by bicknellr** [comment]
> I still see glitches sometimes

Do you mean that it still occasionally focuses the items when you select them?

**Comment by jpodwys** [comment]
If by "when you select them," you mean when `.selected = 0` runs, it appears that way, yes. But I haven't confirmed that's what's happening.

**Pull request closed without merging**
